language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7

        - os: linux
          sudo: required
          python: 3.5

install:
    # via https://github.com/angr/angr/issues/52
    - pip install -I --no-use-wheel capstone
    - pip install --upgrade pep8 pytest-cov pytest
    - pip install -e .

script:
    - find . -name \*.py -exec pep8 --ignore=E501 {} \;
    - py.test ./tests/ -v --cov=idb